Bump PHPStan dependency to 0.12
Roave/no-floaters pull request #18
Opened 2019-12-12 13:24 UTC by lookyman

This would of course need a new major version.

2019-12-12 13:30 UTC, ondrejmirtes commented
Great work! :)

> of course need a new major version

I don't think so. Dependency bump is not a BC break. People depending on ^1.0 and on PHPStan 0.11 would continue using version that still supports it.

What I'm missing in this PR is that PHPStan analysis itself could now run on level 8.

2019-12-12 13:39 UTC, lookyman commented
> People depending on ^1.0 and on PHPStan 0.11 would continue using version that still supports it.

True.

> What I'm missing in this PR is that PHPStan analysis itself could now run on level 8.

It runs without arguments on Travis, so I think it already is on level 8?

2019-12-12 13:43 UTC, ondrejmirtes commented
Nope: https://github.com/Roave/no-floaters/blob/master/phpstan.neon.dist#L11

2019-12-12 13:46 UTC, lookyman commented
Now it is 😊

2019-12-12 13:52 UTC, ondrejmirtes commented
The ComposerRequireCheck build failure is because PHPStan is now distributed as PHAR. ComposerRequireCheck cannot reason about it. I removed it from PHPStan extensions because of this. (Not sure how hard would it be to fix this issue in it.)

2019-12-12 15:02 UTC, Ocramius requested changes

2019-12-12 15:02 UTC, Ocramius commented on src/DisallowFloatAssignedToVariableRule.php
> +    public function processNode(Node $node, Scope $scope) : array // phpcs:ignore SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification
A type declaration for the type being returned, or an `{@inheritDoc}`, are required

2019-12-12 15:02 UTC, Ocramius commented on src/DisallowFloatEverywhereRule.php
> +    public function processNode(Node $node, Scope $scope) : array // phpcs:ignore SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification
Same as above: type is required here, or at least an `{@inheritDoc}`

2019-12-12 15:02 UTC, Ocramius commented on src/DisallowFloatInFunctionSignatureRule.php
> +    public function processNode(Node $node, Scope $scope) : array // phpcs:ignore SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification
Same as above: an `{@inheritDoc}` should suffice

2019-12-12 15:02 UTC, Ocramius commented on src/DisallowFloatInMethodSignatureRule.php
> +    public function processNode(Node $node, Scope $scope) : array // phpcs:ignore SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification
Same as above: an `{@inheritDoc}` should suffice

2019-12-12 15:02 UTC, Ocramius commented on src/DisallowFloatPropertyTypeRule.php
> +    public function processNode(Node $node, Scope $scope) : array // phpcs:ignore SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingTraversableReturnTypeHintSpecification
Same as above: an `{@inheritDoc}` should suffice

2019-12-12 15:03 UTC, Ocramius commented
> ComposerRequireCheck cannot reason about it.

How are classes autoloaded in the new package? Just loading the entire phar?

2019-12-12 15:08 UTC, ondrejmirtes commented
If you're only using PHPStan-referencing code when running PHPStan, the autoloader from inside the PHAR is used.

If you're referencing PHPStan code when not running PHPStan, so for example for the rules unit tests, then this gets executed: https://github.com/phpstan/phpstan/blob/master/bootstrap.php#L29-L36

When some prefixed dependency gets required when not running PHPStan, then this is executed: https://github.com/phpstan/phpstan/blob/master/bootstrap.php#L9-L16 (this will also most likely happen when running RuleTestCase because part of PHPStan gets booted and used)

2019-12-12 15:15 UTC, Ocramius commented
Yeah, I think that's impossible to check for `ComposerRequireChecker` for now, unless we completely switch to BetterReflection there. Even then, the `ComposerRequireAutoloader` is deprecated, as it is unsafe to load third party scripts to perform autoloading of unknown sources.

I think it is safe to drop it from the CI pipeline and dependencies here, @lookyman.

2019-12-12 15:26 UTC, lookyman commented
@Ocramius Done.

2019-12-12 15:40 UTC, Ocramius commented
Ouff, `roave/backwards-compatibility-check` also cannot find these classes :-( This entire phar business is a massive headache...

I'll think about a solution for that

2019-12-12 15:49 UTC, ondrejmirtes commented
Why? They can be autoloaded by Composer itself...

2019-12-12 15:53 UTC, Ocramius commented
These are not in deterministic locations, declared via a composer package definition, but rather through a custom autoloader.

I understand the reason why this is done, it just isn't something usable by tooling, which is understandable too.

2020-01-28 07:45 UTC, fezfez commented
Any news ?

2020-01-28 11:08 UTC, Ocramius commented
the BC check won't work at all right now, sorry - can't merge in current state.

Either we completely drop it (this is only infrastructure implementing upstream types, after all), or we find a way to make this work with PHARs (rabbit hole)

2020-01-28 12:10 UTC, ondrejmirtes commented
I'm for merging this and tagging the next minor release. We can solve the infrastructure another time, it's apparent this code works and people would benefit from it.

2020-01-28 12:53 UTC, Ocramius commented
If @lookyman can remove the check from CI, then we should be OK to merge then.

I think PHAR introspection in better-reflection may never actually happen, unless someone wants to maintain it.

2020-01-28 13:38 UTC, lookyman commented
Ok, I'll do that later today.

2020-01-28 16:45 UTC, Ocramius approved these changes
LGTM :+1:

2020-01-28 16:45 UTC, merged

2020-01-28 16:46 UTC, Ocramius commented
And released: https://github.com/Roave/no-floaters/releases/tag/1.3.0

2020-01-28 18:18 UTC, fezfez commented
Thanks all!