Handle "never" type as non float
Roave/no-floaters pull request #24
Opened 2022-08-16 12:14 UTC by fmata

As `MixedType`, `NeverType` implements `CompoundType` witch always returns yes on `isSubTypeOf()` calls. It forbids the use of `never` native PHP type (or as annotation) with this extension.

2022-08-16 12:27 UTC, Ocramius requested changes
Just need an explanation, or some clarity, about how `FloatTypeHelper::isFloat()` is tested here :thinking:

2022-08-16 12:35 UTC, fmata commented
AFAIK the helper `FloatTypeHelper` is not tested directly but many tests cover it since it is used everywhere (`DisallowFloatInFunctionSignatureRule` and `DisallowFloatInMethodSignatureRule` for my use case). Without my modification in `FloatTypeHelper`, the tests with my new fixtures in `tests/asset` fail.

2022-08-16 13:35 UTC, Ocramius commented
@fmata so, to be clear, if we drop the changes to `FloatTypeHelper`, CI should go red, right?

2022-08-16 13:36 UTC, Ocramius commented
Wait... CI didn't run at all :O

2022-08-16 13:38 UTC, fmata commented
> @fmata so, to be clear, if we drop the changes to `FloatTypeHelper`, CI should go red, right?

Absolutely.

Tests are successful on my side but didn't run here :innocent:

2022-08-16 13:47 UTC, Ocramius commented
I'll have to fix that before a release :D

2022-08-17 17:35 UTC, merged

2022-08-17 17:37 UTC, Ocramius commented
OK, even post-merge, CI didn't run.

Something is fishy 🤔

2022-08-17 17:38 UTC, Ocramius commented
Released meanwhile: https://github.com/Roave/no-floaters/releases/tag/1.6.0

2022-08-17 18:08 UTC, fmata commented
Thanks!